### ISSUE TITLE
Allow to define config/environment path so we can test Engines

### ISSUE THREAD

**Issue by fabiokr** [cucumber/cucumber-rails#102]
On Rails3 engines, what we normally have is a dummy test application. The problem is that cucumber-rails expects to find the config/environment.rb always on the project root. So, in order to be able to have a features folder on my project root and run the features using the dummy application, the config/environment path should be somehow configurable.

**Comment by andrewhavens** [comment]
Add this to the top of your `features/support/env.rb`:
```ruby
ENV["RAILS_ENV"] ||= "test"
require File.expand_path("../../../spec/dummy/config/environment.rb", __FILE__)
ENV["RAILS_ROOT"] ||= File.dirname(__FILE__) + "../../../spec/dummy"
```

**Comment by Kosmas** [comment]
@andrewhavens would you like to do a pull request for this?
