### ISSUE TITLE
database_cleaner missing gem, still fails on strategy

### ISSUE THREAD

**Issue by jaylevitt** [cucumber/cucumber-rails#127]
After a rails generate cucumber:install on Rails 3.0.6, cucumber-rails 0.4.1, Ruby 1.9.2p180, OS X 10.6.7, I get the following with "rake cucumber":

```
You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it. (RuntimeError)
/Users/jay/src/tiptap/2t2/features/support/env.rb:37:in `rescue in <top (required)>'
```

Once I add database_cleaner to the Gemfile, I instead get:

```
  undefined method `connections' for DatabaseCleaner:Module (NoMethodError)
  /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/cucumber-rails-0.4.1/lib/cucumber/rails/hooks/database_cleaner.rb:8:in `Before'
```

and

```
  Please set a strategy with DatabaseCleaner.strategy=. (DatabaseCleaner::NoStrategySetError)
  /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/database_cleaner-0.5.2/lib/database_cleaner/configuration.rb:82:in `strategy'
  /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/database_cleaner-0.5.2/lib/database_cleaner/configuration.rb:69:in `start'
  /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/cucumber-rails-0.4.1/lib/cucumber/rails/hooks/database_cleaner.rb:30:in `Before'
```

The default env.rb does set a strategy:

```
begin
  DatabaseCleaner.strategy = :transaction
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end
```

I'm not sure how to proceed. I'm using PostgreSQL on dev and production, but SQLite3 on test.

**Comment by singh08avinash** [comment]
my database_cleaner is not working. So what i have to do now?
I include gem database_cleaner in gemfile and include in env.rb also
"begin
    require 'database_cleaner'
  require 'database_cleaner/cucumber'
  DatabaseCleaner.strategy = :transaction
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end
"

after that my database_cleaner is not working...

**Comment by xtrasimplicity** [comment]
@singh08avinash  What does the `gem "database_cleaner"` area of your `Gemfile` look like?
