### ISSUE TITLE
Cucumber only showing Capybara errors

### ISSUE THREAD

**Issue by aaronmcadam** [cucumber/cucumber-rails#260]
I keep having an annoying issue with Cucumber. If there are any errors in the Controller, it only shows the errors raised by capybara. I'm sure that's not the way it used to work?

For example, if an exception was raised, the only output I see is: `expected to find css "h1" with text "blah"`

In order to actually see the error, I have to `puts page.body` in order to see the Controller error

Is this expected behaviour?

**Comment by segantii-alex-falkowski** [comment]
Any traction on this?

**Comment by aaronmcadam** [comment]
@segantii-alex-falkowski Are you seeing the same issue? I've recently moved away from cucumber as nobody outside of engineering was writing gherkin, but I've got some legacy features I could check for this.

**Comment by segantii-alex-falkowski** [comment]
Yep I am seeing this issue. We just tail the logs. Though I thought I would raise just so you guys know :)

**Comment by aaronmcadam** [comment]
I would suggest raising a new issue with what you're seeing and closing this one since it was raised Aug 23, 2013.

**Comment by aaronmcadam** [comment]
Including an example Rails app demonstrating the problem will help your issue get solved much more quickly
