### ISSUE TITLE
Cucumber executable should be in bin folder under Rails 4

### ISSUE THREAD

**Issue by kramerdog** [cucumber/cucumber-rails#277]
I did a 
      rails generate cucumber:install 
on a new Rails 4 project today and noticed that the cucumber file was still placed in the script folder.

My understanding is that the script folder is no longer utilised for Rails 4 and all "executables" are now stored in the bin folder (with rake, rails and bundle).

So shouldn't the generator now be placing the cucumber executable in the bin folder?

ruby 2.0.0p353
rails 4.0.3
cucumber 1.3.10
cucumber-rails 1.4.0
OS Win64

**Comment by vindia** [comment]
So what's the status for this issue? When I'm on Rails 4 can I just manually remove `script/cucumber` and replace it with the `bin/cucumber` from https://github.com/dnrce/tracks/blob/7d7e47deffe6e0c628ccaa6f910750fab8040370/bin/cucumber? (Yes, I'm using Spring)

**Comment by Kosmas** [comment]
@vindia there was no progress on this. If you would like to do a PR you're more than welcome :-)

**Comment by Kosmas** [comment]
@vindia i think you can have a look at this one if you want: https://github.com/cucumber/cucumber-rails/pull/314

**Comment by vindia** [comment]
@Kosmas Thanks! From #314 I get that the entire file is not needed at all, right?

**Comment by Kosmas** [comment]
@vindia not quite sure if that is the case but you can have a play around to see if it works. Have also a look at the comment that @tooky left about rspec-rails.

**Comment by asartalo** [comment]
Rails 5 doesn't use the script folder too.

**Comment by luke-hill** [comment]
As this repo hasn't integrated the stale/lockbot. I'm going to close this issue off, given the majority of stuff Mentioned is several versions out of date and we've also began to drop support for older rails / ruby versions in `cucumber-rails`

If the OP still has an issue with an up to date version of the gem and rails then feel free to open a new issue
