### ISSUE TITLE
cucumber.rake should execute db:test:clone not test:prepare

### ISSUE THREAD

**Issue by kramerdog** [cucumber/cucumber-rails#278]
As I just mentioned in $277 I did a 
      rails generate cucumber:install 
on a new Rails 4 project today and couldnt work out why running rake cucumber didnt rebuild my test database

It took me ages to figure out but it seems that the Rails team have silently restructured the way that all of the Rake tasks work for cloning the structure of the development database to a freshly built test database.

From what I can tell the test:prepare task used to rebuild the test database. Now it appears from 
...\lib\ruby\gems\2.0.0\gems\activerecord-4.0.3\lib\active_record\railties\databases.rake

that prepare is now only the task to 'Check for pending migrations and load the test schema'

I had to update all occurrences of test:prepare in cucumber.rake, such as in:

```
Cucumber::Rake::Task.new({:wip => 'test:prepare'}, 'Run features that are being worked on') do |t|
  t.binary = vendored_cucumber_bin
  t.fork = true # You may get faster startup if you set this to false
  t.profile = 'wip'
end
```

with db:test:clone to get rake cucumber to rebuild my test database prior to running mu cucumber features.

So shouldn't the cucumber.rake task generated now be using db:test:clone?

I should note that I am using

```
config.active_record.schema_format = :sql
```

in application.rb

and also had to add the line to application.rb:

ActiveRecord::Base.schema_format = config.active_record.schema_format

as a workaround as ActiveRecord::Base.schema_format was still being evaluated as :ruby in the clone task of databases.rake and is supposed to evaluate as :sql as a result of my config setting

ruby 2.0.0p353
rails 4.0.3
cucumber 1.3.10
cucumber-rails 1.4.0
OS Win64

**Comment by luke-hill** [comment]
Apologies for dredging up a *seriously* old topic. But figured given we will drop rails 4 support soon for cucumber-rails (We only support 4.2 at the moment as a minimum), I was wondering if this is still an issue.

I had a brief look into the things linked here, and from what tooky said about adding an additional task to the default is definitely not a problem. Is this something you would want?

cc/ @kramerdog @joallard

**Comment by joallard** [comment]
Yeah, it's been too long, I don't think this is relevant to me anymore.

**Comment by luke-hill** [comment]
I'll keep monitoring this for a while then close if appropriate.
