### ISSUE TITLE
Cucumber not running migration/maintaining test schema

### ISSUE THREAD

**Issue by joallard** [cucumber/cucumber-rails#291]
I originally commented the following in #278, but I think this deserves its own issue for tracking purposes:

> Probably relevant: rails/rails#13528 and [`ActiveRecord::Migration.maintain_test_schema!`](https://github.com/rails/rails/pull/13528/files#diff-96b8e5694f7954d018d9958ef89f4049R18)

Following the Rails PR, my schema doesn't update anymore and I'm currently trying to find a way to update my test schema to continue working. Pretty major if you ask me.

**Comment by Kosmas** [comment]
@joallard sorry for not replying earlier.

Yes, it's been an earlier issue that somehow got left behind.
There was a change in the way the test schema was created in the latest rails versions.

I will go back and look at the earlier issue, but using the schema load as you have used it, should be the recommended way to do it.

**Comment by luke-hill** [comment]
As the linked issues have been merged in and this hasn't had any updates in over 4 years I'm going to close it. If the issue still exists on a later version of cucumber-rails / rails feel free to open a new post.
