### ISSUE TITLE
Release a new stable gem version with Cucumber 2 support

### ISSUE THREAD

**Issue by tuxayo** [cucumber/cucumber-rails#298]
Or put in the readme a commit hash considered as stable as the currently published gem. Just to reassure those who are afraid to depend on the latest master commit.

**Comment by christemple** [comment]
+1

**Comment by lukad** [comment]
:+1:

**Comment by rstawarz** [comment]
+1 - Is there something blocking this from happening, and how can I help move it forward if so?

**Comment by Kosmas** [comment]
@rstawarz the only thing that is blocking it is available time. If you want to do a PR, it would be great :-)

**Comment by tuxayo** [comment]
Can we safely consider the current HEAD as releasable?

**Comment by Kosmas** [comment]
@tuxayo The gemspec has cucumber < 2.1, so as long as Travis agrees, then I don't see why not.

**Comment by tuxayo** [comment]
Does anyone else than you can release a new gem on rubygems.org?

**Comment by zillou** [comment]
+1

**Comment by moeabdol** [comment]
+1

**Comment by kevgo** [comment]
+1

**Comment by tompave** [comment]
+1

**Comment by DannyBen** [comment]
I am sure many more people are waiting for this, and just don't want to overcrowd this thread with +1s. Any chance one of the contributors can provide some official statement on the matter?  Or if it is no longer maintained, maybe someone else can take over / fork?

**Comment by Kosmas** [comment]
Hi all, 
I'm very sorry for not replying earlier.
The issue at the moment is that none of the tests are passing on Travis.
I've tried a couple of times to see the reason why, but unfortunately I've run out of time, as I'm quite busy at the moment.
If anyone is willing to have a look and then do a PR, I'm quite happy to do a release.
As far as I remember there was an issue with the autoloader.

**Comment by mattwynne** [comment]
Hi everyone,

I'm sorry we're doing a poor job of keeping this library up to date. I'm afraid I personally stopped using Rails some time ago, so my own need for this library to be functional has gone.

That said, me and the rest of the Cucumber team care a huge amount about the Ruby community generally, and the Rails community are obviously a big part of that :heart:

This library obviously needs more love and maintenance, and I'm happy to give new contributors all the support they need to change, clean up and release this code with confidence. I'd like to find people who're actually using it day-to-day, so you've got that direct connection to the user base in a way that I don't.

Is anyone willing to step forward to help @Kosnas carry this load?

**Comment by DannyBen** [comment]
Thank you both for the clear statement and attention, I am sure it is appreciated and anticipated by everybody here. It is good at least to know where things stand even if its not the perfect answer we all wanted.

I am using this library on a daily basis, but I am not sure I have the necessary skills to assist. I promise I will at least take a look to see if there is any way I can help (at least if no one more capable steps in in front of me... :)

**Comment by tooky** [comment]
I've just pushed this branch: https://github.com/cucumber/cucumber-rails/tree/support-cucumber-2.x%2B

Using that I can run cucumber in a rails 4.2 project. I can't run the tests though. It would be great to figure out a better way to test cucumber-rails.

**Comment by tooky** [comment]
@Kosmas are we able to release a new gem now? Anything I can help with?

**Comment by Kosmas** [comment]
@tooky yes we are able to. I've just sent some messages yesterday for the existing PRs, if anyone wants to include them before releasing the new version.
So maybe in a day or two we can release it.
Thank you, but I think now with the tests fixed, everything is fine. :-)
Will let you know if there's anything you can help with, though !

**Comment by tooky** [comment]
:+1:

**Comment by tuxayo** [comment]
@Kosmas Thanks !
