### ISSUE TITLE
Rails 4.2.3 rails engine will drop test database when running cucumber

### ISSUE THREAD

**Issue by wellsonjain** [cucumber/cucumber-rails#301]
Hello everyone, 

Recently I got this issue. I move my model layer and db/migration to rails engine, and setup my test database with seed data. When I start to run cucumber, it start to drop the table and re-do migration. If I did the same this but removing the append_migrations block in engine.rb. When I start to run cucumber, it work properly.  Should I make more setting for engine, like add path or something like that? 

Here is my setting: https://gist.github.com/wellsonjain/790f40a6b299f09776ce

**Comment by dkowis** [comment]
I suggest you use the cucumber google group to get support. This is a bug tracker for verifyable bugs with the software. You'll have better luck there.

See https://cucumber.io/support
