### ISSUE TITLE
Description of scenario

### ISSUE THREAD

**Issue by chrisokamoto** [cucumber/cucumber-rails#309]
I'm getting this error with this new version:
undefined method `description' for #<Cucumber::Core::Test::Case

I use the property "description" of a scenario (scenario.description) and now I can't access this property.. Did you change the way to access it?

**Comment by Kosmas** [comment]
@chrisokamoto I haven't personally changed this.
Not quite sure if any of the PRs has changed it, but maybe is something that change with the new version of cucumber?

**Comment by chrisokamoto** [comment]
Yes, it has changed with the new version.. the property "title" has changed too.. but in the terminal appeared a message to change "title" to "name" and it worked.. In the case of the property "description" you didn't provide a workaround...

**Comment by Kosmas** [comment]
@chrisokamoto maybe you can raise in issue in the cucumber project about it and describe what you have described here, or create a PR :-)

**Comment by chrisokamoto** [comment]
Humm I thought the problem was with Cucumber-Rails because it has updated to version 1.4.3 a few days ago.. And after that these things stopped working... But I'll investigate.. Thanks!!

**Comment by luke-hill** [comment]
Closing as irrelevant.

The keyword method you need is `scenario.name`

If you want to find out other methods run the following command

`scenario.methods - Object.methods` -> This will yield a reasonable level. Or explore them in the blob tree on GH.
