### ISSUE TITLE
Gemfile.lock is being recreated when the Rails environment starts

### ISSUE THREAD

**Issue by roberts1000** [cucumber/cucumber-rails#310]
I'm not sure if this is a cucumber-rails issue or an issue with one of the dependencies.  Around March 3rd we started noticing that our Gemfile.lock file was being recreated when we started the rails server or ran our automated tests.  We have the following in our Gemfile

```
group :test do
  gem "cucumber-rails", "1.4.3", require: false
end
```

The Gemfile.lock is modified to remove the following gems

```
-    cucumber-core (1.3.1)
-      gherkin3 (~> 3.1.0)
-    cucumber-wire (0.0.1)
-    event-bus (0.1.0)
-    gherkin3 (3.1.2)
```

If I change the gem version to 1.4.2 the problem goes away.  If I leave 1.4.3 in place, delete Gemfile.lock and try to a do a full bundle, bundler generates a Gemfile.lock with the above gems in place.  As soon as I start the rails server, the Gemfile.lock is modified again.  I'm not sure why the version of cucumber-raiils would matter when starting the rails server (since it's not in the :development group and require is false).

We're using Puma as the primary development server and Rails is 4.2.5.2.  I've verified this problem exists with Webrick and Unicorn as well.

**Comment by Kosmas** [comment]
@roberts1000 when you say that you started noticing the change around the 3rd of March, is it because that's when it started happening or maybe it was happening before but you did not notice it?

The latest version was released at the end of January, so it's a little over a month before you started noticing it?

Have you tried to create a new simple program and see if it happens there too?

**Comment by roberts1000** [comment]
It started happening around March 3rd.  I've been developing in this app full time for the past several months so it stood out once it started happening.  I get the feeling the real issue is somewhere in one of the dependent gems that cucumber-rails pulls in (or it's an issue in our app).

I'm going to dig a little deeper to try and figure out why it's present in 1.4.3, but not 1.4.2.

**Comment by xtrasimplicity** [comment]
Is this still an issue? If not, I'll close it off. :)

**Comment by roberts1000** [comment]
I just closed it out.  :)
