### ISSUE TITLE
Having Problems using poltergeist and cucumber/rails when using sequel in rails 

### ISSUE THREAD

**Issue by HoneyryderChuck** [cucumber/cucumber-rails#318]
I was reading poltergeist documentation that there are problems across threads and sharing transactions across threads. I'm migrating a project from AR to sequel. 

When I had AR, there was never an issue with running javascript feature tests. 

I wonder it's because of this: https://github.com/cucumber/cucumber-rails/blob/master/lib/cucumber/rails/hooks/active_record.rb#L1-L8

How could I reproduce/patch this for sequel?

**Comment by Kosmas** [comment]
@TiagoCardoso1983 so do you actually have a problem now with sequel.

And when you are talking about sequel what exactly do you mean?

**Comment by TiagoCardoso1983** [comment]
humm, it's a combination of dependencies, as this is only failing in the javascript tests (I'm using poltergeist as driver). Apparently, server runs in a background thread, the pools are created by thread and that causes issues depending on the strategy one uses to clean the database (using database_cleaner).

I saw there was one "hack" for AR (the shared connection thing) and I'm not sure if this is the reason why it worked with AR, and it doesn't work anymore with sequel, which might require a similar hack.

**Comment by xtrasimplicity** [comment]
Is this still an issue? If not, do you mind if we close this? Thanks!

**Comment by HoneyryderChuck** [comment]
Not really, mostly solved it by avoiding cucumber altogether. Problem solved
