### ISSUE TITLE
Zero assertions

### ISSUE THREAD

**Issue by pauloancheta** [cucumber/cucumber-rails#325]
assertions remain 0 even though there is 1 scenario.

<img width="423" alt="screen shot 2016-09-11 at 2 53 29 pm" src="https://cloud.githubusercontent.com/assets/9355943/18420783/91d72c58-782f-11e6-820c-437209b19dd3.png">

**Comment by Kosmas** [comment]
Have you got the code somewhere?
Is that for a new project?

**Comment by mattwynne** [comment]
The assertions line is not coming from Cucumber.

I've seen something like this before when a project was somehow requiring `minitest` as part of their run.
