### ISSUE TITLE
Use default_url_options from ApplicationController

### ISSUE THREAD

**Issue by maxnitze** [cucumber/cucumber-rails#327]
The `_path` methods available in the step definitions are not using the `default_url_options` method from the `ApplicationController`. I found threads suggesting to use support files like this:

```
# features/support/fix_localization.rb
# workaround, to set default locale for ALL spec
class ActionDispatch::Routing::RouteSet
  def default_url_options options={}
    { locale: I18n.locale }.merge options
  end
end

class ActionDispatch::Integration::Session
  def default_url_options options={}
    { locale: I18n.locale }.merge options
  end
end

class ActionDispatch::IntegrationTest
  def default_url_options options={}
    { locale: I18n.locale }.merge options
  end
end
```

My problem is, that I set the default url options based on the current logged in user. Here's the excerpt from my `ApplicationController`:

```
def default_locale
  current_user ? current_user.locale : I18n.default_locale
end

def default_url_options options={}
  (I18n.locale.to_s.eql?(default_locale) ? { locale: nil } : { locale: I18n.locale }).merge options
end
```

I alredy figured out, that I can use the following setup for my unit tests:

```
class ActionView::TestCase::TestController
  def default_url_options options={}
    subject.default_url_options options
  end
end
```

So is it possible to do anything similar to specify, that the `_path` helpers in my features use the `default_url_options` method from the `ApplicationController`?

**Comment by Kosmas** [comment]
@maxnitze please use the user groups for questions. This is an issue tracker.
Thanks
