### ISSUE TITLE
ruby 2.3.1 /.../n has a non escaped non ASCII character in non ASCII-8BIT script (RegexpError)

### ISSUE THREAD

**Issue by stevelake** [cucumber/cucumber-rails#330]
I'm getting the following error messages when attempting to run tests in ruby 2.3.1 which were developed under ruby 1.9.3...
/.../n has a non escaped non ASCII character in non ASCII-8BIT script (RegexpError)
c:/Ruby23/lib/ruby/gems/2.3.0/gems/tmail-1.2.7.1/lib/tmail/utils.rb:117:in `<module:TextUtils>'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/tmail-1.2.7.1/lib/tmail/utils.rb:110:in `<module:TMail>'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/tmail-1.2.7.1/lib/tmail/utils.rb:53:in `<top (required)>'
c:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
c:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/tmail-1.2.7.1/lib/tmail/interface.rb:36:in `<top (required)>'
c:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
c:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/tmail-1.2.7.1/lib/tmail/mail.rb:34:in `<top (required)>'
c:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
c:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/tmail-1.2.7.1/lib/TMail.rb:2:in `<top (required)>'
c:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
c:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
c:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
c:/workspace/KGB_QA_Automation/features/support/env.rb:12:in `<top (required)>'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load_code_file'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:142:in `load_file'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:84:in `block in load_files!'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `each'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `load_files!'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:253:in `load_step_definitions'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:61:in `run!'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
c:/Ruby23/bin/cucumber:23:in `load'
c:/Ruby23/bin/cucumber:23:in `<main>'

I can see the offending lines in the utils.rb class of the ruby gem (lines 110-117) in question are...
  module TextUtils

    aspecial     = %Q|()<>[]:;.\\,"|
    tspecial     = %Q|()<>[];:\\,"/?=|
    lwsp         = %Q| \t\r\n|
    control      = %Q|\x00-\x1f\x7f-\xff|

    CONTROL_CHAR  = /[#{control}]/n

**Comment by Kosmas** [comment]
@stevelake if the error is in the ruby gem, you should be reporting this there instead of here.
https://github.com/cucumber/cucumber-ruby
