### ISSUE TITLE
@request and @response not accessible in cucumber world.

### ISSUE THREAD

**Issue by jayaram2701** [cucumber/cucumber-rails#331]
I'm using cucumber for doing integration testing. Since, cucumber-rails runs in the context of 
ActionDispatch::IntegrationTest. I thought "assert_redirect_to" and other response assertions will work.
But , it throws an error saying @request class is not the expected type.

Please help me with this.

**Comment by Kosmas** [comment]
@jayaram2701 please use the cucumber list for questions like that (https://groups.google.com/forum/#!forum/cukes)
