### ISSUE TITLE
Records Created in When is not visible in Then methods

### ISSUE THREAD

**Issue by jayaram2701** [cucumber/cucumber-rails#332]
I'm using Database::Cleaner Transaction strategy.
Also, tried with the hack for having a single connection for all threads, but still the records are not visible. 
class ActiveRecord::Base
  mattr_accessor :shared_connection
  @@shared_connection = nil

  def self.connection
    @@shared_connection || ConnectionPool::Wrapper.new(:size => 1) { retrieve_connection }
  end
end

**Comment by Kosmas** [comment]
@jayaram2701 please use the cucumber list for questions like that (https://groups.google.com/forum/#!forum/cukes)
