### ISSUE TITLE
Drop support for older Rails versions?

### ISSUE THREAD

**Issue by mvz** [cucumber/cucumber-rails#333]
I've been trying to update the development dependencies to a more recent version of Aruba, and I found this is very hard to do in a clean way, since dependencies of Rails 3.0 and 3.1 indirectly force the use of Aruba 0.8.

Since Rails 3.0 and 3.1, and even 3.2, are ancient and unsupported, I would propose dropping support for it. People stuck on those platforms can simply use cucumber-rails 1.45 or earlier.

This would also allow for cleaning up of the generation of `script/cucumber` (#277), which can be replaced by a recommendation of the `spring-commands-cucumber` gem.

WDYT?

**Comment by Kosmas** [comment]
@mvz I think that is a good idea and it makes sense.
Please go ahead!

**Comment by mvz** [comment]
The implementation of this is ready in #334.

**Comment by Kosmas** [comment]
Thank you @mvz
