### ISSUE TITLE
Support for Rails 5.1.0

### ISSUE THREAD

**Issue by zhanglinjie** [cucumber/cucumber-rails#339]
Because cucumber-rails relies on railsties (< 5.1), and with Rails 5.1.0's version of railsties being 5.1.0, cucumber-rails cannot install on Rails 5.1.0.

**Comment by esambo** [comment]
See: _Support Rails 5.1 #337_

**Comment by Davidslv** [comment]
Would it be possible to release a new version of `cucumber-rails` on rubygems please?

Thank you

**Comment by Kosmas** [comment]
new version 1.5.0 released.
