### ISSUE TITLE
Additional "test" output when running Cucumber features

### ISSUE THREAD

**Issue by andypearson** [cucumber/cucumber-rails#342]
I've just setup a fresh Rails 5.1 application using `cucumber-rails`.

When I run my features using `bundle exec cucumber` I get the usual output, but then at the end it looks like it also tries to run some tests with a different test framework:

```
2 scenarios (2 passed)
5 steps (5 passed)
0m5.779s
Run options: --seed 29966

# Running:



Finished in 0.001350s, 0.0000 runs/s, 0.0000 assertions/s.

0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

This doesn't seem to happen when a feature fails.

**Comment by luke-hill** [comment]
Hi @andypearson I'm aware this is an insanely aged issue, but is this still an issue and if so do you have a reproducible case (Ideally a small github repo)

**Comment by andypearson** [comment]
@luke-hill I can't even remember what project I was working on when I had this problem, so I think it's safe to say it can be closed :D
