### ISSUE TITLE
has a non escaped non ASCII character in non ASCII-8BIT script

### ISSUE THREAD

**Issue by jake-doss** [cucumber/cucumber-rails#350]
I'm having a lot of trouble solving this problem. I've looked on the other related issues but none of those solutions are fixing my problem. I have the #encoding: ASCII at the top of my code_128.rb file and all i'm trying to do is 

def generate_barcode
    barcode = Barby::Code128C.new(@order.id)
    outputter = Barby::PrawnOutputter.new(barcode)
    barcode.annotate_pdf(self, height: 20, xdim: 0.5, x: 420, y: 684)
    outputter.height = 10
    outputter.ydim = 50
  end

I have these included at the top of the file as well:

require 'rubygems'
require 'barby'
require 'barby/barcode/code_128'
require 'barby/outputter/png_outputter'
require 'barby/outputter/prawn_outputter'
require 'barby/outputter/ascii_outputter'

**Comment by olleolleolle** [comment]
@jake-doss It seems you've reported a Barby-related issue in the wrong repository?

Perhaps you want to ask your questions in that community? https://github.com/toretore/barby 

They can probably help you way better.

Good luck!
