### ISSUE TITLE
Cucumber expressions not implemented

### ISSUE THREAD

**Issue by songsta** [cucumber/cucumber-rails#351]
Hi

I've been trying to use the [Cucumber Expressions](https://cucumber.io/blog/2017/07/26/announcing-cucumber-expressions) but it doesn't seem to be implemented with this gem yet. 

My Gherkin feature:  Given I'm logged in as an admin

My Step Definition:  Given "I'm logged in as a(n) {string}" do |role|

....

end

When I run this I get:

You can implement step definitions for undefined steps with these snippets:

Given(/^I'm logged in as an admin$/) do
  pending # Write code here that turns the phrase above into concrete actions
end

I"m using Rails 5.1.4 and the cucumber-rails 1.5.0.

**Comment by TALlama** [comment]
@songsta the `string` parameter type is quoted, so you'd have to use `Given I'm logged in as an "admin"` (single quotes work, too), use the `word` parameter type instead, or create your own.

**Comment by aslakhellesoy** [comment]
Thanks for explaining @TALIama!
