### ISSUE TITLE
Update README about Ruby versions

### ISSUE THREAD

**Issue by olleolleolle** [cucumber/cucumber-rails#361]
This section of the README now refers to quite an old Ruby version: is this still the correct wording?

https://github.com/cucumber/cucumber-rails#setting-up-your-environment

@xtrasimplicity I'm pinging you on this, it's because you've got the latest on which versions are recommended.

**Comment by xtrasimplicity** [comment]
Yep, that's way outdated. I'll update that soon - thanks!
