### ISSUE TITLE
Error from generated cucumber.yml file

### ISSUE THREAD

**Issue by margOnline** [cucumber/cucumber-rails#365]
I am using rails 5.0.6, ruby 2.2.5p319, cucumber 3.1.0

I set up the cucumber-rails gem with bundle and `rails generate cucumber:install`.  The following cucumber.yml was generated:
```
<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags ~@wip"
%>
default: <%= std_opts %> features
wip: --tags @wip:3 --wip features
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip
```

After setting up my features and step definitions, when I ran `cucumber features`, I received the following error.
`Failed describing child of #<Cucumber::Core::Ast::Feature "[my feature]" (features/my_feature.feature:1)> - Empty stack (RuntimeError)`

I changed the cucumber.yml file to
```
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict"
%>
default: <%= std_opts %> features
```
and all works nicely. 

I'm raising the issue to:
1.  highlight a fix to others who have a similar issue
2. ask if the initial install can generate a different cucumber.yml

**Comment by lisimba** [comment]
@margOnline I came across this exact issue and wasn't sure what the problem was. However, your suggestion fixed it! Thanks

**Comment by xtrasimplicity** [comment]
I ran into this issue on a Rails 4.2 app today after upgrading to cucumber-rails v1.6.0 - it was easily resolved by re-running `bundle exec rails g cucumber:install` and opting `no` for files that I'd modified, as [suggested in the Readme file](https://github.com/cucumber/cucumber-rails#upgrading-from-a-previous-version).

If this doesn't help, could you please [create  a MCVE](https://stackoverflow.com/help/mcve) demonstrating this issue and post it here, so that we can take a look?

**Comment by luke-hill** [comment]
Hi @margOnline - Just doing a bit of a tidy and this issue is nearly a year old. Are you still having the issues mentioned after the suggestions from :point_up: ??

If you're no longer experiencing these issues we can close this issue off.

**Comment by margOnline** [comment]
> If you're no longer experiencing these issues we can close this issue off.
I have not had the opportunity to install cucumber to an app since I'm working on existing apps.

**Comment by luke-hill** [comment]
In an effort to tidy things up I'll close this off.

If people still have similar issues they can re-open a new ticket.
