### ISSUE TITLE
Tests sporadically fail with 'Unable to connect to mozilla geckodriver' errors

### ISSUE THREAD

**Issue by xtrasimplicity** [cucumber/cucumber-rails#370]
## Summary

Most of the time, the tests pass without any issues, however, occasionally they fail with `unable to connect to Mozilla geckodriver 127.0.0.1:4445 (Selenium::WebDriver::Error::WebDriverError)`.
See https://github.com/cucumber/cucumber-rails/pull/369#issuecomment-374029643 for reference.
## Expected Behavior

The tests will pass continuously.

## Current Behavior

Tests sporadically fail with:
```
unable to connect to Mozilla geckodriver 127.0.0.1:4445 (Selenium::WebDriver::Error::WebDriverError)
```

## Possible Solution
This is often caused by Firefox upgrades leading to incompatibilities with a specific version of Selenium WebDriver, but given the sporadicity of this issue, I don't imagine this would be the cause.

## Steps to Reproduce (for bugs)

1. Rerun the tests on CI.
2. Cross your fingers and hope they fail. ;)

**Comment by radar** [comment]
I  have a suspicion that this is due to a Geckodriver / Firefox incompatibility. Which would be strange!

I am trying to reproduce this over on travis-ci.org/radar/cucumber-rails, but I am quickly running out of time today to see if I can fix this issue.

I suspect that https://github.com/gobijan/cucumber-rails/pull/5 _might_ fix these issues. I don't know for certain!

**Comment by xtrasimplicity** [comment]
@radar  Thanks heaps for working on this. Unfortunately, it hasn't resolved the issue - but I think we should merge the other PR anyway, as it won't impact on a user's ability to use the new release. We can continue to temporarily circumvent it by restarting the failing jobs.

I'll leave this issue open. :)

**Comment by xtrasimplicity** [comment]
Looking at the errors with `geckodriver -V`, and the source code in `geckodriver-helper`, it is failing to download the latest `geckodriver` binary.

In a different branch, I've updated the travis CI config file to download `geckodriver` directly, extract it, run the daemon (rather than have Selenium trigger the daemon). It seems to be working well, so fingers crossed!

**Comment by radar** [comment]
Could it potentially be failing because it is hitting GitHub’s API limit?

**Comment by xtrasimplicity** [comment]
[For future reference: @radar  has submitted a PR to [DevicoSolutions/geckodriver-helper](https://github.com/DevicoSolutions/geckodriver-helper)

**Comment by xtrasimplicity** [comment]
The PR upstream has been merged and has been released to rubygems.org!

**Comment by radar** [comment]
Great! Thanks for following this up @xtrasimplicity

**Comment by xtrasimplicity** [comment]
Not a problem at all! :)
