### ISSUE TITLE
Support capybara 3.0 in gemspec file

### ISSUE THREAD

**Issue by jasnow** [cucumber/cucumber-rails#379]
## Summary

Change "capybara (>= 1.1.2, < 3)" to support capybara 3.0.

## Expected Behavior

Support capybara 3.0.

## Current Behavior

Support only capybara < 3.0.

## Possible Solution

Change this line in https://github.com/cucumber/cucumber-rails/blob/master/cucumber-rails.gemspec:
```
 s.add_runtime_dependency('capybara', ['>= 1.1.2', '< 3'])
```

## Steps to Reproduce (for bugs)

You can see the dependency limits on https://rubygems.org/gems/cucumber-rails

## Context & Motivation

Can't upgrade to latest capybara gem.

## Your Environment

N/A

**Comment by xtrasimplicity** [comment]
Thanks for reporting this, @jasnow. We currently have an open PR to support Capybara < 4, and Rails 5.2, so hopefully we will be able to release a fix for this soon. :) 

https://github.com/cucumber/cucumber-rails/pull/378

**Comment by jasnow** [comment]
@xtrasimplicity - Therefore this is a duplicate so I will close it. Thanks for the heads up.
