### ISSUE TITLE
error

### ISSUE THREAD

**Issue by singh08avinash** [cucumber/cucumber-rails#382]
hi, I want to login with a user through query.
First i create feature file and i create query after that i fill the text file then i click login button after that its goes to the user dashboard page after that its show error
"Then I should be on the dashboard page # cucumber-websteps-0.10.0/lib/cucumber/websteps/browsing_steps.rb:56
expected: "/welcome/dashboard"
got: "/users/sign_in" (using ==) (RSpec::Expectations::ExpectationNotMetError)
./features/support/env.rb:94:in block in <top (required)>' features/login.feature:10:inThen I should be on the dashboard page'"

I want to perform some other action after login

**Comment by xtrasimplicity** [comment]
Hi @singh08avinash,

It looks like the login process hasn't actually logged in you in, so your app is redirecting you to the login page.

I would recommend having a read through the documentation listed on the following sites:
https://github.com/cucumber/cucumber/wiki, https://docs.cucumber.io.
The latest documentation, still under development, can be found on https://cucumber.netlify.com/

If you still experience issues, please have a look at the support options available to you. We also have a slack channel where we can help you through this.
https://cucumber.io/support

As this doesn't appear to be an issue with cucumber-rails itself, I'm going to close this issue off.

Good luck! :)
