### ISSUE TITLE
Error after login

### ISSUE THREAD

**Issue by singh08avinash** [cucumber/cucumber-rails#383]
hi, I want to login with a user through query.
First i create feature file and i create query after that i fill the text file then i click login button after that its goes to the user dashboard page after that its show error
"Then I should be on the dashboard page # cucumber-websteps-0.10.0/lib/cucumber/websteps/browsing_steps.rb:56
expected: "/welcome/dashboard"
got: "/users/sign_in" (using ==) (RSpec::Expectations::ExpectationNotMetError)
./features/support/env.rb:94:in block in <top (required)>' features/login.feature:10:inThen I should be on the dashboard page'"

I want to perform some other action after login

can i show my code to you because i don't known what is error?
After create user i print user details on terminal and its shows your user created but after login break the page

**Comment by xtrasimplicity** [comment]
`expected: "/welcome/dashboard"
got: "/users/sign_in"`

This means that the Cucumber test was expecting to have been redirected to `/welcome/dashboard`, but was redirected to the login page. I recommend making sure that the user login process is working correctly. 

Again, Github issues are for reporting bugs with Cucumber. As this isn't a bug with cucumber, please read the documentation I posted in a previous comment and have a read of 
https://cucumber.io/support


I will close this issue. Please do not create another issue for support-related issues.
