### ISSUE TITLE
The functionality of database cleaner has been integrated to rails since 5.1

### ISSUE THREAD

**Issue by LionelLindt** [cucumber/cucumber-rails#406]
## Summary

The functionality of the `database-cleaner` gem has been integrated to rails since `5.1`. I therefore think, it shouldn't be used by `cucumber`.

## Expected Behavior

I expect `cucumber` to work without the `database-cleaner` gem, like rails system tests do too since version `5.1`.

## Current Behavior

When I run a `cucumber` feature test without `database-cleaner`, some test won't work.

## Context & Motivation

I'd like to use `cucumber` without the `database-cleaner` gem because it is an additional dependency and it is not needed since rails `5.1`

**Comment by luke-hill** [comment]
It's a valid point. But technically at the moment Rails 4.2 is our lowest supported version. So we'd need to keep supporting it until Rails 5.1 becomes our lowest supported version (I've no idea when this is likely to be, but conservative estimates would be at least another year)

**Comment by coorasse** [comment]
I find this a relevant point. Why can't we have support for Rails 5.1 System tests and keep requiring database_cleaner for 4.2? Is there an impediment for that?

**Comment by luke-hill** [comment]
We could do. But does it provide value....

If someone raised a PR I could review it, but it's not something I'd work on at the moment

**Comment by coorasse** [comment]
I think it would provide quite an added value: remove the dependency from database_cleaner. The system tests provided by Rails work with transactions (and not truncation or deletion of the database), therefore are also faster.
I understand this is not something you might be willing to do, but if you consider this a valid point and you are willing to accept PRs maybe someone else can take a look into it 👍

**Comment by luke-hill** [comment]
My knowledge of rails is weak, but from what the OP originally said is that, this functionality is provided by default from `5.1`

What I'm saying is `5.1` is not the lowest version we support, it's `4.2`, so we would need some conditional. Which I don't think makes sense. We should just wait until `5.1` is the lowest version and then delete the dependency?

**Comment by luke-hill** [comment]
@coorasse is this something you were wanting to work on, or just something you were asking about? Just wondering whether to keep this issue open or not. If it adds value to keep it open I'm not against it. Just the timeline for removing rails 4.2 and 5.0 is essentially non-existent.

**Comment by coorasse** [comment]
Hi @luke-hill, I'd like to help you but this is not a priority for me at the moment. I don't think dropping `database_cleaner` would be an impediment in supporting Rails 4.2 and 5.0 but I don't know enough about the project to point exactly at the changes that are needed. Maybe @LionelLindt has time to tackle this. I'd not close the issue since this is still an open point but that's up to you. Thanks for your time! 🙇

**Comment by luke-hill** [comment]
Just from a quick scan of the codebase there is only 2 places where it's directly called, one of which is rescued and one of which is on a options flag. So in my eyes this technically is already possible (But I've not tried it).

Using the command `install_cucumber_rails(:no_database_cleaner)` should suffice. See here for code stack: https://github.com/cucumber/cucumber-rails/blob/master/features/step_definitions/cucumber_rails_steps.rb#L29

I'm going to close this as available in cucumber-rails 1.7 if there are additional problems, feel free to re-open another issue.
