### ISSUE TITLE
Cut a version (1.7 I think?)

### ISSUE THREAD

**Issue by luke-hill** [cucumber/cucumber-rails#407]
ping @mvz @olleolleolle @xtrasimplicity - Can we maybe look at doing this before anything else is merged in.

Last release was >6 months ago and the number of commits is 50+, probably should do something about this.

As this isn't managed under the cucumber monorepo it "should" be theoretically easier to do also.

I don't think any additional changes are needed, just CHANGELOG scanning and cutting / pushing the gem.

P.S. For now I'd rather not promote this works with 6.0.0.beta1 for rails, as it is just that a beta. Maybe when there's a full RC or something we can do this.

**Comment by mvz** [comment]
I'll take a look at what's needed for this in the coming days.

**Comment by mvz** [comment]
@luke-hill I'd like to at least not install `cucumber` to `script/cucumber` anymore. Perhaps we should just not install anything, and tell users to either `bundle binstubs cucumber` or install `spring-commands-cucumber`?

**Comment by xtrasimplicity** [comment]
Sorry, just saw this. I'm pretty swamped at the moment, but will take a look if I get a moment. To anyone else with release abilities, feel free to go ahead with this in the meantime, if you get to it before I do. :)

**Comment by luke-hill** [comment]
I've got some time this coming week. I'll cut the release first on the repo. And then if we have a (short) embargo of merging additional items so I can go through and write the relevant items (Changelog / release notes e.t.c.), I'll get that done.

**Comment by mvz** [comment]
Thanks for looking to into this, @luke-hill. I've been meaning to get around to this but haven't, so I'm glad you're picking this up.

**Comment by xtrasimplicity** [comment]
Thanks for releasing that, @luke-hill. Do you have release rights to rubygems.org? If not, let me know and I can push it up for you. 👍

**Comment by luke-hill** [comment]
I don't @xtrasimplicity if you want to checkout to master or v1.7.0 and push it up that would be epic, or grant karma, whatever is easier.

**Comment by xtrasimplicity** [comment]
Thanks, @luke-hill. All done. :)
