### ISSUE TITLE
Examples Table how to allow for additional "|"

### ISSUE THREAD

**Issue by Srutherford2407** [cucumber/cucumber-rails#422]
Cucumber Rails:

I am attempting to write a Scenario where data is being generated into our application. We have a unique instance where the text being entered contains | which is throwing off my table. Is there was to ignore the extra | I am adding?

```  
        Examples:
            | BusinessPartner | DealTag  | DealTitle                               | BadgeText         | Description   | SearchTerms                                                           | InPerson | Online | OnlinePromoCode | OnlineWebsite                                          | Phone |
            | Aaron's Deil    | Food     | **15% off Food Delivery Monday - Thursday | 11 am - 2 pm**| Monday - Thursday | 11 am - 2 pm  | 15% off food Delivery Monday – Thursday, 11 am - 2 pm. Carry out only |          | Yes    | No              |                                |       | No |```

The line with the ** around it, I need the | to be passed as part of the text and not seen as a new column is this possible?

**Comment by luke-hill** [comment]
This is likely something which would need to be fixed in the gherkin parser. I'm reasonably confident this can't be done currently, but I can defer to a lead on it. I'll ask in the committers channel on slack

**Comment by luke-hill** [comment]
```
IIRC "\|" (in for example Examples tables) will interpret the "|" as part of the cell content instead of as a cell delimiter.
```

From slack. Do you want to try that?

**Comment by Srutherford2407** [comment]
@luke-hill Just tested and I got the follow:
From my data table `15% off Food Delivery Monday Thursday "\|" 11 am - 2 pm`

Output to console:

`Then("Create new Deals add Info {string} {string} {string}|{string} {string} {string}") do |string, string2, string3, string4, string5, string6|`

Current Scenario:

`Then Create new Deals add Redemption Options "<SearchTerms>" "<InPerson>" "<Online>" "<OnlinePromoCode>" "<OnlineWebsite>"`

**Comment by Srutherford2407** [comment]
@luke-hill  Thanks for the help! Looks like removing the " " and \| works to add the | as text within my tests. Thanks a ton!
