### ISSUE TITLE
V2 plan - thoughts?

### ISSUE THREAD

**Issue by luke-hill** [cucumber/cucumber-rails#435]
v1.8 (Soon). - Just cut what we've got. Technically apart from olle's change this is a bug fix release. But targetting only 2.3 presents itself as an easy way of cutting a v1.8
**v1.8 now on rubygems**

v2
- Removing web_steps. (Breaking change)
- Alter script locations (Breaking change)
- Update rails stuff to use physical vers
- Any other small things

Thoughts @olleolleolle / @xtrasimplicity / @mvz / anyone else?

**Comment by mvz** [comment]
Looks like a good plan to me.

One thing I'd like to add is updating stuff so that the cucumber binstub appears in bin/ instead of scripts/. Or maybe we can drop that entirely and just let `spring-commands-cucumber` handle it. I guess I should make an issue for that :thinking:.

**Comment by mvz** [comment]
Here is a new issue about that: #438.

**Comment by luke-hill** [comment]
Updated the OP to include everything we're doing.

The next release will be a 2.0

**Comment by luke-hill** [comment]
Now the next release is confirmed to be 2.0 we can close this and just continue working until we cut the ver
