### ISSUE TITLE
Generated cucumber script is in outdated location

### ISSUE THREAD

**Issue by mvz** [cucumber/cucumber-rails#438]
## Summary

Cucumber-rails generates `script/cucumber`, but recent versions of Rails put helpers scripts in `bin/`. Cucumber-rails should do the same.

## Expected Behavior

Upon installing cucumber-rails, there's a file `bin/cucumber` for running the scenarios.

## Current Behavior

Instead, there's a file called `script/cucumber`.

## Possible Solutions

1. Change the target location of `script/cucumber` to `bin/cucumber`.
2. Depend on `spring-commands-cucumber` and have that generate `bin/cucumber`

There are probably other options. We can see how `rspec-rails` does things.

## Context & Motivation

It's an annoyance to have to move this file manually or install `spring-commands-cucumber` myself.

**Comment by luke-hill** [comment]
Seems logical. And easy to slot into a v2 release :)

**Comment by luke-hill** [comment]
As we've released a v2 this would go into a v3 release, but still can be done whenever you've got time @mvz

**Comment by mvz** [comment]
@luke-hill I don't see v2 in rubygems? Did the gem push succeed?

**Comment by luke-hill** [comment]
I've not pushed it yet. There's been some issues in terms of keys e.t.c. we've been trying to sort out for a while. I think we're close though. It'll be up soon

**Comment by luke-hill** [comment]
Obviously as a heads up this would need to be in a v3 release @mvz but there's nothing stopping us making that the next release. Given the lengthy time it's been (Things quiet on the western front).

**Comment by luke-hill** [comment]
This is in `main` and will be released with v3 proper in a couple of weeks.
