### ISSUE TITLE
`install_cucumber_rails` & Other legacy methods: Tidy up / Lint

### ISSUE THREAD

**Issue by luke-hill** [cucumber/cucumber-rails#439]
Minor tidy to method to improve linting and use new syntax

## Expected Behavior

Should use new ruby 2.3+ syntax

## Current Behavior

Use Ruby 1.9 or older syntax

## Possible Solution

Update syntax

**Comment by luke-hill** [comment]
Partially fixed by #441 but need to put into better layout (private methods e.t.c.), not a massive huge chunky one.

**Comment by aslakhellesoy** [comment]
What needs to be done to close this issue @luke-hill ?

**Comment by luke-hill** [comment]
Not really sure. I can check on friday as I've got most of the day to go into this. If memory serves me right #441 was a tidy up of really bad syntax / standards. But I think I only fixed half of it. (Due to time / complexity).

**Comment by luke-hill** [comment]
I'll just close this now. As it's working and tidier than it was after that OP.
