### ISSUE TITLE
DatabaseCleaner 1.8.x deprecates DatabaseCleaner.connections, which cucumber-rails uses

### ISSUE THREAD

**Issue by christiannelson** [cucumber/cucumber-rails#459]
## Summary

`DatabaseCleaner.connections` has been deprecated in the 1.8.x versions of DatabaseCleaner. The deprecation is triggered from cucumber rails on this line: https://github.com/cucumber/cucumber-rails/blob/a33bf05bf060339091af54a7f6019d48eba31b5d/lib/cucumber/rails/database.rb#L79

## Expected Behavior

No deprecation warning when using the latest DatabaseCleaner versions.

## Current Behavior

~~~
Calling `DatabaseCleaner.connections` is deprecated, and will be removed in database_cleaner 2.0. Use `DatabaseCleaner.cleaners`, instead.
~~~

## Possible Solution

Call `DatabaseCleaner.connections` on older versions of DatabaseCleaner and `.cleaners` on newer ones. I'm not 100% certain when cleaners was introduced though.

## Context & Motivation

We like to have warning-free test runs. :) 

## Your Environment

* Version used: `cucumber-rails (2.0.0)`
* Operating System and version: `macOS 10.15.3`
* Link to your project: N/A

**Comment by luke-hill** [comment]
Whilst everything in this report is fair, it's probably worth noting we still officially support rails 4.2 (And I'm not sure what version of Cleaner is tied to what version of rails).

Putting in some branching logic is quite easy though, so this ticket will be worked on, we just need to cover our bases.

**Comment by mathieujobin** [comment]
I'm in the progress of upgrading a rails 4.2 app and I just bumped database_cleaner to 1.8 without any problems.
