### ISSUE TITLE
CI Failures (Rails 6.0.1)

### ISSUE THREAD

**Issue by luke-hill** [cucumber/cucumber-rails#461]
## Summary

Fix the issues on Rails 6 on CI

## Expected Behavior

CI passes

## Current Behavior

CI fails
## Possible Solution

Created an issue in Rails (Unsure if it will gain traction) - https://github.com/rails/rails/issues/38502

## Steps to Reproduce (for bugs)

1. Check CI with rails 6.0.0 - It passes
2. Check CI with rails 6.0.1 - It fails
3.
4.

## Context & Motivation

Get CI green again

## Your Environment

CI here

**Comment by olleolleolle** [comment]
Could it be that sassc takes so long that it's too long for us? (Is there a trick to not include that gem?)

**Comment by luke-hill** [comment]
It's a valid point.

In march I'm gonna have another month of OSS'ing so I'll try triage and fix a few of these issues. I've just not had much time these last 2 months.
