### ISSUE TITLE
Drop `git` from gemspec

### ISSUE THREAD

**Issue by utkarsh2102** [cucumber/cucumber-rails#475]
Hi,

Thanks for working on this! :heart: 
However, while maintaining this in Debian, we found that this library relies on git to list the files (which could be done via pure Ruby alternative):

https://github.com/cucumber/cucumber-rails/blob/9b8f155174f1c7e6150f57cfa75422f06fe42e2b/cucumber-rails.gemspec#L48-L49

I'd be happy to raise a PR if you concur in dropping git from gemspec :smile: 
Let me know what you think!?

**Comment by luke-hill** [comment]
Go for it, if you have the time. It's not something really high priority, but I'd review and merge.

**Comment by utkarsh2102** [comment]
Thanks, Luke, opened as #476 :rocket:
