### ISSUE TITLE
Too restrictive version numbers

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-rails#481]
The version numbers in `cucumber-rails.gemspec` are arbitrary: https://github.com/cucumber/cucumber-rails/blob/208949b8645f592ea43bfa3ceff7b1b20f357bcf/cucumber-rails.gemspec#L25-L29

I can't think of a good reason for the `cucumber` dependency to be `'>= 3.0.2', '< 5'`. Why is it OK to use version `4` and not `5`?

One option is to follow semver and say `~> 3.0`. This way we don't risk breaking changes.

Another option is to simply say `>= 3.0` with no upper limit. This is more risky, but also lower maintenance. We wouldn't have to make a new cucumber-ruby release every time a new cucumber major release is made (unless it's backwards incompatible in a way that breaks cucumber-rails).

**Comment by luke-hill** [comment]
So we wanted to allow cucumber version 4 as we had tested it and validated it worked. I kind of like the principle we have at the moment. As if a version 5 came out, we should test it, then validate it works and allow it

(As version 5 came out recently, this is something we should do).

I'm not keen on no upper limit. I'm happy to look at / prioritise the "need" for cucumber5 usage. But I know it's still quite new.

**Comment by aslakhellesoy** [comment]
Aha I see! I think we should add a comment in the gemspec to explain why the version ranges are the way they are then.

Maybe related: https://github.com/cucumber/cucumber-ruby/issues/1467

**Comment by luke-hill** [comment]
Sounds like a good idea. I did something similar recently with travis, I'll do the same here some time soon.

**Comment by ucguy** [comment]
@luke-hill 
>I'm happy to look at / prioritise the "need" for cucumber5 usage. But I know it's still quite new.

Since this was brought up here, just want to mention that our team is attempting to upgrade from `cucumber 3.2.0`. 
However, there was a bug introduced in `4.0.0` that was subsequently fixed only in version `5.0.0`:
See issue: https://github.com/cucumber/cucumber-ruby/issues/1445
and changelog: https://github.com/cucumber/cucumber-ruby/blob/master/CHANGELOG.md#fixed-3

When we attempted to update to `cucumber 5.0.0`, we were forced to downgrade `cucumber-rails` from `2.1.0` to _`1.4.0`_.
This is when we noticed the restrictive version numbers from `cucumber-rails` end. 
That downgrade in itself was not that big a deal, the main problem was running into the following error on our CI: 

```
Found tagged hook with '~@javascript'.'~@tag' is no longer supported, use 'not @tag' instead. (RuntimeError)
/home/circleci/code/recruit/vendor/bundle/gems/cucumber-5.0.0/lib/cucumber/glue/hook.rb:56:in `block in fail_for_old_style_tag_expressions'
/home/circleci/code/recruit/vendor/bundle/gems/cucumber-5.0.0/lib/cucumber/glue/hook.rb:54:in `each'
/home/circleci/code/recruit/vendor/bundle/gems/cucumber-5.0.0/lib/cucumber/glue/hook.rb:54:in `fail_for_old_style_tag_expressions'
/home/circleci/code/recruit/vendor/bundle/gems/cucumber-5.0.0/lib/cucumber/glue/hook.rb:17:in `initialize'
/home/circleci/code/recruit/vendor/bundle/gems/cucumber-5.0.0/lib/cucumber/glue/registry_and_more.rb:75:in `new'
/home/circleci/code/recruit/vendor/bundle/gems/cucumber-5.0.0/lib/cucumber/glue/registry_and_more.rb:75:in `register_rb_hook'
/home/circleci/code/recruit/vendor/bundle/gems/cucumber-5.0.0/lib/cucumber/glue/dsl.rb:23:in `register_rb_hook'
/home/circleci/code/recruit/vendor/bundle/gems/cucumber-5.0.0/lib/cucumber/glue/dsl.rb:66:in `Before'
/home/circleci/code/recruit/vendor/bundle/gems/cucumber-rails-1.4.0/lib/cucumber/rails/hooks/active_record.rb:14:in `<main>'
```

So unless I'm missing something, it is not possible to use cucumber 5.0.0 as it is right now with any version of `cucumber-rails`
Just curious if anyone else ran into this issue upgrading to cucumber 5.

**Comment by aslakhellesoy** [comment]
Yes, exactly what I had predicted which is why I created this issue. I think we should make a new release where we relax the dependencies to `~> major.minor`.

Any takers?

**Comment by luke-hill** [comment]
Being dealt with in #482 - Should be merged this week. Afterwards I'll try get something cut.

**Comment by ucguy** [comment]
Thank you @luke-hill for merging #482. 
I see that the `2.1.0` dependency [has been updated to be `<6` ](https://github.com/cucumber/cucumber-rails/commit/8ebf772a49ba955b18904ee8afe3d8e125517b19#diff-5bacb7ff9bc30c91a517ad25b85d4498R26)

However, I'm still hitting the restriction when I try to upgrade to cucumber 5.0.0 while maintaining `cucumber-rails 2.1.0`
And rubygems.com is showing that the dependency remained un-updated:
![Screen Shot 2020-10-01 at 2 04 03 PM](https://user-images.githubusercontent.com/15618931/94863246-fefc9d00-03ee-11eb-92d4-3f7d6b0710d8.png)

Is there something else you are waiting on?

**Comment by luke-hill** [comment]
Nope. I'll try cut something in the next couple of days. Just need to update changelog and get keybase all working on my main VM.
