### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-rails#492]
We should migrate from Travis to GitHub Actions. Travis is no longer supporting Open Source.

**Comment by mathieujobin** [comment]
Very sad to see Travis keeping digging its own grave.

Does Circle-CI supports opensource? Should we consider gitlab pipelines?

I'm used to GitHub for development, but I feel GitHub Actions is a long term lock in

**Comment by aslakhellesoy** [comment]
> Does Circle-CI supports opensource

Yes, and so does GH Actions. Most of this org’s builds are already using GitHub Actions, so I’d prefer to use that - it integrates nicely with github.

> Should we consider gitlab pipelines?

I’d rather not. I don’t want to fragment our platforms more.

> I feel GitHub Actions is a long term lock in

How? If we want to move to a different CI system, we’ll just add a nee config and delere the GHA one.

**Comment by mathieujobin** [comment]
Alright. Thanks for your reply
