### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by madejejej** [cucumber/cucumber-rails#494]
There's a GPL-licencing issue going on in Rails now - https://github.com/rails/rails/issues/41750

Since `cucumber-rails` v2.2.0 depends on `rails`, it technically is also GPL-licensed.

However, there was a PR to master that changed the dependencies https://github.com/cucumber/cucumber-rails/pull/486. The `master` branch only depends on `railties` and `activerecord`. This change mitigates this issue because `activestorage` and `actionmailbox` are the only Rails gems that depend on `mimemagic`.

**Comment by luke-hill** [comment]
Yep, will be spoken about in our meeting. I can get on this tomorrow. Shouldn't be a lot of blockers.

**Comment by paulhklam1122** [comment]
@madejejej thanks for bringing this up, yes I'm experience an issue running bundle install on CircleCI. Failing at installing `cucumber-rails`. Had to update the rails 5.2.5 to get around the `mimemagic` issue which broke our CI build. P.S. using `
ruby 2.6.6`

**Comment by luke-hill** [comment]
This is in flight. To anyone reading the issue. There will be an update soon.

**Comment by luke-hill** [comment]
cucumber-rails 2.3.0 is released on rubygems
