### ISSUE TITLE
Support for Rails 7

### ISSUE THREAD

**Issue by erikaxel** [cucumber/cucumber-rails#523]
Rails 7 has been released and it would be great if cucumber-rails could support it. 

I did an initial "fix" where I just relaxed the gemspec requirement and added test runners for 7.0 in https://github.com/erikaxel/cucumber-rails/commit/6b225611fad8af12780f3718bd9f9c63327c4462
However that seems to be insufficient since a couple of tests fail. I'm not very familiar with this project so I'm a bit stumped on where to continue. Happy to help if I can, but it would be great with some pointers on where to start. The errors on the CI can be seen here: https://github.com/erikaxel/cucumber-rails/actions/runs/1587333272
 
PS: Also happy to make my initial commit with tests running on 7.0 into a PR if that is helpful.

**Comment by luke-hill** [comment]
You're a bit keen on the gun :) But yes I will get to this as/when appropriate.

I fully expect the next 2/3 weeks to have little to no uptake (% wise), of rails 7. So we should have some time on our hands.

**Comment by benny-burkhart** [comment]
Something in the dependencies might need an update -- I ended up with 1.4.0 first.
![image](https://user-images.githubusercontent.com/11530347/146694446-7137cab3-8818-48b4-8647-aa3d9be7ed46.png)

**Comment by luke-hill** [comment]
Yes, as we are discussing, your PR isn't quite valid.

As a bare minimum we need to check
- New CI
- Existing features (Think we have 3/4 breakages)
- Any caveats with the rails "fake" installs.

**Comment by benny-burkhart** [comment]
Hmmm I can see that CI doesn't seem to cover Rails 7... Do you know where to add that?

**Comment by luke-hill** [comment]
Yes, there is already a spiked branch and PR above. If you check the OP.

**Comment by tagliala** [comment]
Hi @erikaxel ,

I've investigated two of the three failures

```
cucumber features/capybara_javascript_drivers.feature:3 # Scenario: Use Browser UI backed by DB
cucumber features/capybara_javascript_drivers.feature:88 # Scenario: Use Browser UI without a DB
```

depend by the fact that Rails 7 generates a form with a `form.datetime_field :when`, so it has a modern datetimepicker and so the cucumber rails helper is not able to find date component dropdowns.

A possible fix:

```diff
diff --git a/features/capybara_javascript_drivers.feature b/features/capybara_javascript_drivers.feature
index 271639d..92f4f6b 100644
--- a/features/capybara_javascript_drivers.feature
+++ b/features/capybara_javascript_drivers.feature
@@ -4,6 +4,7 @@ Feature: Capybara Javascript Drivers
     Given I have created a new Rails app and installed cucumber-rails
     And I force selenium to run Firefox in headless mode
     When I run `bundle exec rails g scaffold appointment name:string when:datetime`
+    When I run `sed -i -e 's/datetime_field/datetime_select/' app/views/appointments/_form.html.erb`
     And I write to "features/create_appointment.feature" with:
       """
       @javascript
@@ -89,6 +90,7 @@ Feature: Capybara Javascript Drivers
     Given I have created a new Rails app and installed cucumber-rails without database_cleaner
     And I force selenium to run Firefox in headless mode
     When I run `bundle exec rails g scaffold appointment name:string when:datetime`
+    When I run `sed -i -e 's/datetime_field/datetime_select/' app/views/appointments/_form.html.erb`
     And I write to "features/create_appointment.feature" with:
       """
       @javascript
```

**Comment by luke-hill** [comment]
If that's the issue, then the desired solution would be to amend the datepicker and select the datepicker in 2 different ways.

**Comment by tagliala** [comment]
Hi @luke-hill , thanks

I don't know if I will have time, but the third and last failure can be fixed in a similar way (following a different path when it runs on Rails 7)

**Comment by luke-hill** [comment]
Thanks for triaging. It'll make it easier as/when someone picks it up. I'll look at this in a couple of weeks if no-one gets to it before then.

Atm I imagine the rails7 uptake is miniscule.

**Comment by xanderificnl** [comment]
> Something in the dependencies might need an update -- I ended up with 1.4.0 first. ![image](https://user-images.githubusercontent.com/11530347/146694446-7137cab3-8818-48b4-8647-aa3d9be7ed46.png)

I kept getting hit by '~@javascript' in `active_record.rb` being invalid. After having not considered/realized an older version got installed, I scanned through lots of comments (most dating back 10 years.), looking through commits related to `active_record.rb` it finally did hit me. Version 1.4 got installed. 

In case someone else also hits that issue, and also looks/searches through issues -- hopefully this'll save them some time.

**Comment by luke-hill** [comment]
As mentioned in the earlier posts, this is to be expected. Unfortunately I caught covid over the xmas break.

There have been bits and pieces commits which have fixed part of the issue. But essentially this just needs working on.

**Comment by mathieujobin** [comment]
Not sure if this help, but I made this branch to get me forward, I was hoping to open a PR, but it isn't complete.

`github: 'mathieujobin/cucumber-rails', branch: 'rails7'`

- Added Rails 7 to the test suite - e85fb17a98a6b02fda407ec21832e32a1af26d32
- ruby 2.5 fails, probably because I bumped bundler, funny though is ruby 2.4 pass fine
- rails 7 fails with the 3 fore-above mentioned tests.
- removed support for rails 5.0 and 5.1, ruby 2.4 and 2.5 6af6bf12dc50d0daeae03d6d264675a9c43a387a 971dfd9c9cb719c9507b7b86d010b702bc4bc60c
- used workaround for 2/3 of the test failures as suggested in this issue 188c00b603cc2c5180aef7fd9f6aa80fecd90e96

**Comment by mgrunberg** [comment]
I made #526 based on the [tagliala comments](https://github.com/cucumber/cucumber-rails/issues/523#issuecomment-998118841) but with a different workaround. mathieujobin, sorry for not continuing your branch but I wanted to take a different approach and leave drop old rails and ruby support for a separate PR.
