### ISSUE TITLE
Date input support in Rails 7

### ISSUE THREAD

**Issue by ollietreend** [cucumber/cucumber-rails#534]
The PR #526 by @mgrunberg, which was created to resolve issue #523, introduced the assumption that Rails 7 will always render date fields as `<input type="date">`. However, it's still possible for Rails 7 to render `<select>` based date inputs.

According to the [Rails Form Helpers guide](https://guides.rubyonrails.org/form_helpers.html#using-date-and-time-form-helpers):

> If you do not wish to use HTML5 date and time inputs, Rails provides alternative date and time form helpers that render plain select boxes.

There are now two officially supported form helper methods:

- `form.date_field` will output `<input type="date">` (new in Rails 7)
- `form.date_select` will output `<select>` fields (traditional Rails date input)

However when using Rails 7, only `<input type="date">` fields are supported because:

https://github.com/cucumber/cucumber-rails/blob/fa07f579ea05f6e925ff4c3ac6785214ef66e961/lib/cucumber/rails/capybara/select_dates_and_times.rb#L11-L20

### 👓 What did you see?

Cucumber no longer knows how to select dates for input fields created with `form.date_select` in Rails 7.

### ✅ What did you expect to see?

Cucumber should still be able to select dates, regardless of whether `form.date_field` or `form.date_select` was used in Rails 7.

### 📦 Which version are you using?

- cucumber-rails 2.5.0
- Rails 7

### 🔬 How could we reproduce it?

1. Install Rails 7 with cucumber-rails 2.5.0
2. Render a form with a date field created using `form.date_select`
3. Cucumber cannot select a date for this field

**Comment by luke-hill** [comment]
So what we missed with this was extra cucumber tests to validate both options still worked. I'll add these in to start with and then we can go about rectifying this.

**Comment by ollietreend** [comment]
@luke-hill @mgrunberg Thank you both for the super quick work on this! ⭐ 🙇🏻 It's really appreciated.

Is it going to make its way into a release shortly?

**Comment by luke-hill** [comment]
I'll give it a few days to see if any other things come out. But I can try cut a bugfix release for this soon
