### ISSUE TITLE
`cucumber-rails` incompatible with latest `cucumber-ruby`

### ISSUE THREAD

**Issue by kmarcisz** [cucumber/cucumber-rails#538]
### 👓 What did you see?
When updating to latest `cucumber-ruby` I couldn't jump to version 8 without dropping to much older version of `cucumber-rails`.

```
root@00fe90130848:/usr/src/app# bundle update --conservative cucumber cucumber-rails
(...)
Fetching cucumber 8.0.0 (was 7.1.0)
Installing cucumber 8.0.0 (was 7.1.0)
(...)
Fetching cucumber-rails 1.4.0 (was 2.5.1)
Installing cucumber-rails 1.4.0 (was 2.5.1)
(...)
Note: cucumber-rails version regressed from 2.5.1 to 1.
```
### ✅ What did you expect to see?
I expected to see both `cucumber-ruby` and `cucumber-rails` be updated to newest published versions.

### 📦 Which tool/library version are you using?
Rails 7.0.3
Ruby 2.7.6

### 🔬 How could we reproduce it?

1. Set up a new Rails project
2. Add `gem cucumber` to Gemfile
3. Run command `bundle install`
4. See version 1.x of `cucumber-rails` installed and not version 2.x

**Comment by aslakhellesoy** [comment]
So let’s keep this open as a reminder to make cucumber-rails compatible with cucumber-ruby 8.

**Comment by mattwynne** [comment]
Thanks for the feedback @kmarcisz!

Would you like to help us fix it? I guess we just need a new release of `cucumber-rails` with the dependency updated.

If you'd like to book some time to pair on it, you can access my calendar [here](calendly.com/mattwynne/).

**Comment by mattwynne** [comment]
Here we go: #541. Needs a release now.

**Comment by svenwin** [comment]
Just checked out cucumber-rails@main in one of our projects and bumped Cucumber to v8. It's working smoothly out of the box! I just need a release version now 🤣

**Comment by luke-hill** [comment]
Cheers. I'll get on it soon. We've just been fixing up a bunch of stuff with the pipelines e.t.c. so there will be quite a lot of non-package related fixes.

**Comment by kevindew** [comment]
@luke-hill is there any chance this will be released soon?

**Comment by luke-hill** [comment]
Sorry I have been swamped in other stuff and been a bit fluey. I'll get on this soon.
