### ISSUE TITLE
CI Failures - often Bundler/RubyGems, not setup-ruby

### ISSUE THREAD

**Issue by MSP-Greg** [cucumber/cucumber-rails#562]
### 🤔 What's the problem you've observed?

Failing CI, due to older Rubies and the Bundler/RubyGems versions that are included with them.

### ✨ Do you have a proposal for making it better?

One option is https://github.com/MSP-Greg/cucumber-rails/commit/8a27f205a543c1adf7b55f5196168472238da039.  That forces a RubyGems upgrade for all Rubies.  You may want to implement finer control than that, and just upgrade for Ruby 2.6.

### 📚 Any additional context?

See comments in:
https://github.com/cucumber/cucumber-rails/pull/560
https://github.com/cucumber/cucumber-rails/pull/561

and issue https://github.com/ruby/setup-ruby/issues/518#issuecomment-1671746578

**Comment by luke-hill** [comment]
Fixed - will be all good in v3.0.0.rc.1
