### ISSUE TITLE
Support for Cucumber 9

### ISSUE THREAD

**Issue by TALlama** [cucumber/cucumber-rails#573]
### 🤔 What's the problem you're trying to solve?

Cucumber 9 was [released 2023-08-31](https://github.com/cucumber/cucumber-ruby/blob/main/CHANGELOG.md) but `cucumber-rails` is still [restricting to v8](https://github.com/cucumber/cucumber-rails/blob/main/cucumber-rails.gemspec#L25). I did not see an open issue for supporting v9 (there is a [closed one for v8](https://github.com/cucumber/cucumber-rails/issues/538)), so here it is.

### ✨ What's your proposed solution?

The gem should support cucumber v9. I have no idea how much work is involved to to that.

### ⛏ Have you considered any alternatives or workarounds?

We could all stay on cucumber v8 forever, but let's all move into the bright future together.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by luke-hill** [comment]
Yep, it's just one of the things on the list. It was only released a short while ago so it's not that far behind

**Comment by luke-hill** [comment]
@TALlama can you try `v3/version_deps` as a branch.

NB: This branch does do a few experimental things I want to get in for v3.
- First it is based on the existing v3.rc1 branch
- It looks to updating some dev dependencies (No issue expected)
- It updates the permissible cucumber to anything 9.x
- It remedies an issue where the instantiation of the world wasn't auto-calling the `super` initializer (This might cause issues).

**Comment by luke-hill** [comment]
Given no more comments / concerns, I'm going to assume using cucumber 9 on `main` works.

The full v3 cut will permit any version of cucumber 9 with cucumber rails 3.0.0

I'll keep this open as per previous instances until v3 is cut and released on rubygems

**Comment by luke-hill** [comment]
Now permissible in v3
