### ISSUE TITLE
Rails 8 Compatibility (PR attached)

### ISSUE THREAD

**Issue by tagliala** [cucumber/cucumber-rails#589]
### 🤔 What's the problem you're trying to solve?

Upgrading to Rails 8.0

### ✨ What's your proposed solution?

Update gemspec

**Comment by luke-hill** [comment]
Will look to get on this in the next few days @tagliala

**Comment by mgmodell** [comment]
Any updates on this or when it will be posted? Is it a time issue or are there compatibility issues?
